---
# tasks file for nvme

- name: Install nvme-cli
  ansible.builtin.package:
    name: nvme-cli

- name: Set NVMe timeout value to use (Debian Stretch)
  ansible.builtin.set_fact:
    timeout_value: 255
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_release == 'stretch'

- name: Set NVMe timeout value to use (not Debian Stretch)
  ansible.builtin.set_fact:
    timeout_value: 4294967295
  when:
    - ansible_distribution != 'Debian' or ansible_distribution_release != 'stretch'

# Setting this kernel parameter to a high value fixes the bug where
# NVMe volumes occassionally fail and are mounted read-only.
#
# See
# https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/nvme-ebs-volumes.html#timeout-nvme-ebs-volumes
# for more details.
- name: Set NVMe timeout kernel parameter to maximum value
  ansible.builtin.template:
    src: nvme_core.conf.j2
    dest: /etc/modprobe.d/nvme_core.conf
    mode: 0400
  when: ansible_distribution != 'Amazon'
