---
- name: Import upgrade playbook
  ansible.builtin.import_playbook: upgrade.yml

# The kmod package is installed anywhere we would be applying this
# Ansible role
- name: Prepare
  hosts: all
  tasks:
    - name: Install kmod
      ansible.builtin.package:
        name: kmod
